
variables:
  GIT_STRATEGY:                    fetch
  GIT_DEPTH:                       100
  CI_IMAGE:                        "paritytech/ci-linux:production"
stages:
  - test

test:
 script:
   - echo "Hello, world!"
 tags:
 - testlab-runner-1

